public enum AudioType
{
    MUSIC_EXPLORE,
    MUSIC_STAIRS,
    MUSIC_ASCEND,
    MUSIC_UNLOCK,
    SFX_PORTAL_IDLE,
    SFX_PORTAL_USE,
    SFX_PICKUP,
    SFX_INTERACT,
    SFX_STAIRS_TURN,
    SFX_ELEVATOR_DING
}