public enum AudioType
{
    MUSIC_EXPLORE,
    MUSIC_FILLER,
    MUSIC_ASCEND,
    SFX_PORTAL_WHIRR,
    SFX_PORTAL_USE,
    SFX_PICKUP,
    SFX_INTERACT,
    SFX_UNLOCK,
    SFX_STAIRS_TURN,
    SFX_ELEVATOR_DING
}